name: build

on: [push, pull_request]

jobs:
  build-2004:

    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: build_and_test
      run: scripts/build.sh clean

