name: DOOM Retro

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1
      
      - name: Make
        run: scripts/build.sh clean
